version: "3.5"


services:
  statistics:
    build: backend
    container_name: statistics
    command: uvicorn backend.src.core.application:app --host 0.0.0.0 --port 7040
    hostname: statistics
    networks:
      - maininfrnet
    env_file:
      - backend/.env
    ports:
      - 7040:7040
    volumes:
      - ./backend:/backend/


  frontend:
    build: frontend
    container_name: frontend
    hostname: frontend
    networks:
      - maininfrnet
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/

networks:
  maininfrnet:
    external:
      name: infr_network


volumes:
  mongodb: